# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: chalaline-serverless-lambda

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.helloWorld
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: hello-world
          method: get
          cors: true

  createBranch:
    handler: branch/createBranch.createBranch
    events:
      - http:
          path: create-branch
          method: post
          cors: true
  removeBranch:
    handler: branch/removeBranch.removeBranch
    events:
      - http:
          path: remove-branch
          method: post
          cors: true
  listAllBranch:
    handler: branch/listAllBranch.listAllBranch
    events:
      - http:
          path: list-all-branch
          method: get
          cors: true

  addProductToDatabase:
    handler: products/addProductToDatabase.addProductToDatabase
    events:
      - http:
          path: add-product-to-database
          method: post
          cors: true
  addProductToBranch:
    handler: products/addProductToBranch.addProductToBranch
    events:
      - http:
          path: add-product-to-branch
          method: post
          cors: true
  listAllProducts:
    handler: products/listAllProducts.listAllProducts
    events:
      - http:
          path: list-all-products
          method: get
          cors: true
  listPublishedProducts:
    handler: products/listPublishedProducts.listPublishedProducts
    events:
      - http:
          path: list-published-products
          method: get
          cors: true

  registerAsAdmin:
    handler: users/registerAsAdmin.registerAsAdmin
    events:
      - http:
          path: register-as-admin
          method: post
          cors: true
  addStaff:
    handler: users/addStaff.addStaff
    events:
      - http:
          path: add-staff
          method: post
          cors: true
  listStaffs:
    handler: users/listStaffs.listStaffs
    events:
      - http:
          path: list-staffs
          method: get
          cors: true

plugins:
  - serverless-offline